Model location spec
thoughtfront/simple-schedule pull request #8
Opened 2019-01-24 20:43 UTC by RichardLaskowski

#2

2019-01-24 21:18 UTC, cdimoulis requested changes
@RichardLaskowski Looks like this has code that satisfies other issues like #6 Check out the code that is included in this PR and if there are any other completed issues and tag these also. 

However if work still needs to be done on other tickets then don't tag them and we'll do a new branch and PR for those.

2019-01-24 21:25 UTC, RichardLaskowski commented
#3 
#4 
#5 
#6 
#7
This branch includes the previous issue due to being branched from the completed event-model-spec branch

2019-01-24 22:54 UTC, cdimoulis commented on app/models/core/event.rb
> +     :location_id
Didn't we remove this? Just putting there here is like placing a string on a line of code.
Was this potentially in a different branch?

2019-01-24 22:54 UTC, cdimoulis commented on app/models/core/location.rb
> +    :location_id
Didn't we remove this? Different branch? Needs to be removed

2019-01-24 22:58 UTC, cdimoulis commented on spec/models/core/location_spec.rb
> +      expect(test_location.save).to be_truthy
change to `expect(text_location.save).to be(true)`. This function returns true if successful. Of course run the test after making the change and committing.

2019-01-25 15:45 UTC, cdimoulis approved these changes

2019-01-25 15:45 UTC, merged